In [119]:
# Master Time Series table script

In [120]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [121]:
df_1 = pd.read_csv('time_series_19-covid-Confirmed.csv')
df_2 = pd.read_csv('time_series_19-covid-Deaths.csv')
df_3 = pd.read_csv('time_series_19-covid-Recovered.csv')

In [122]:
#dfs = ['df_1', 'df_2', 'df_3']
countries = ['Spain', 'Italy']

In [123]:
df_1a = df_1[df_1['Country/Region'].isin(countries)] 
df_2a = df_2[df_2['Country/Region'].isin(countries)]
df_3a = df_3[df_3['Country/Region'].isin(countries)]

In [126]:
df_1a

,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20
16,Italy,0,0,0,0,0,0,0,0,0,...,2036,2502,3089,3858,4636,5883,7375,9172,10149,12462
18,Spain,0,0,0,0,0,0,0,0,0,...,120,165,222,259,400,500,673,1073,1695,2277

In [125]:
df_1a.drop(['Province/State', 'Lat', 'Long'], axis=1, inplace=True)
df_2a.drop(['Province/State', 'Lat', 'Long'], axis=1, inplace=True)
df_3a.drop(['Province/State', 'Lat', 'Long'], axis=1, inplace=True)

/Users/tadeobarreiro/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [115]:
#for i in dfs:
df_1a['Status'] = 'Confirmed'
df_2a['Status'] = 'Dead'
df_3a['Status'] = 'Recovered'

/Users/tadeobarreiro/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/tadeobarreiro/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/tadeobarreiro/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [116]:
df = df_1a.append(df_2a)
df = df.append(df_3a)

In [117]:
df

,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,Status
16,Italy,0,0,0,0,0,0,0,0,0,...,2502,3089,3858,4636,5883,7375,9172,10149,12462,Confirmed
18,Spain,0,0,0,0,0,0,0,0,0,...,165,222,259,400,500,673,1073,1695,2277,Confirmed
16,Italy,0,0,0,0,0,0,0,0,0,...,79,107,148,197,233,366,463,631,827,Dead
18,Spain,0,0,0,0,0,0,0,0,0,...,1,2,3,5,10,17,28,35,54,Dead
16,Italy,0,0,0,0,0,0,0,0,0,...,160,276,414,523,589,622,724,724,1045,Recovered
18,Spain,0,0,0,0,0,0,0,0,0,...,2,2,2,2,30,30,32,32,183,Recovered

In [98]:
df11 = pd.crosstab(df['Country/Region'], df['1/22/20'], df['1/23/20'])
df11

ValueError: values cannot be used without an aggfunc.

In [95]:
#df1 = df.stack()
#df1

In [96]:
df_1_2 = df_1.transpose()
df_1_2

,0,1,2,3,4,5,6,7,8,9,...,394,395,396,397,398,399,400,401,402,403
Province/State,NaN,NaN,NaN,NaN,NaN,British Columbia,New South Wales,Victoria,Queensland,NaN,...,"Beadle, SD","Charles Mix, SD","Davison, SD","Minnehaha, SD","Bon Homme, SD","Socorro, NM","Bernalillo, NM","Oakland, MI","Wayne, MI","New Castle, DE"
Country/Region,Thailand,Japan,Singapore,Nepal,Malaysia,Canada,Australia,Australia,Australia,Cambodia,...,US,US,US,US,US,US,US,US,US,US
Lat,15,36,1.2833,28.1667,2.5,49.2827,-33.8688,-37.8136,-28.0167,11.55,...,44.4797,43.0985,43.7242,43.6632,42.9815,33.8837,35.0178,42.5922,42.2791,39.5393
Long,101,138,103.833,84.25,112.5,-123.121,151.209,144.963,153.4,104.917,...,-98.2213,-98.3965,-98.2213,-96.8351,-97.8722,-106.724,-106.629,-83.3362,-83.3362,-75.6674
1/22/20,2,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/23/20,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/24/20,5,2,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/25/20,7,2,3,1,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/26/20,8,4,4,1,4,0,3,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1/27/20,8,4,5,1,4,0,4,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1/28/20,14,7,7,1,4,1,4,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1/29/20,14,7,7,1,7,1,4,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1/30/20,14,11,10,1,8,1,4,2,3,1,...,0,0,0,0,0,0,0,0,0,0
1/31/20,19,15,13,1,8,1,4,3,2,1,...,0,0,0,0,0,0,0,0,0,0
2/1/20,19,20,16,1,8,1,4,4,3,1,...,0,0,0,0,0,0,0,0,0,0
2/2/20,19,20,18,1,8,1,4,4,2,1,...,0,0,0,0,0,0,0,0,0,0
2/3/20,19,20,18,1,8,1,4,4,2,1,...,0,0,0,0,0,0,0,0,0,0
2/4/20,25,22,24,1,10,1,4,4,3,1,...,0,0,0,0,0,0,0,0,0,0
2/5/20,25,22,28,1,12,2,4,4,3,1,...,0,0,0,0,0,0,0,0,0,0
2/6/20,25,45,28,1,12,2,4,4,4,1,...,0,0,0,0,0,0,0,0,0,0
2/7/20,25,25,30,1,12,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/8/20,32,25,33,1,16,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/9/20,32,26,40,1,16,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/10/20,32,26,45,1,18,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/11/20,33,26,47,1,18,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/12/20,33,28,50,1,18,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/13/20,33,28,58,1,19,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/14/20,33,29,67,1,19,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/15/20,33,43,72,1,22,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/16/20,34,59,75,1,22,4,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/17/20,35,66,77,1,22,5,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/18/20,35,74,81,1,22,5,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/19/20,35,84,84,1,22,5,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/20/20,35,94,84,1,22,5,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/21/20,35,105,85,1,22,6,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/22/20,35,122,85,1,22,6,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/23/20,35,147,89,1,22,6,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/24/20,35,159,89,1,22,6,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/25/20,37,170,91,1,22,7,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/26/20,40,189,93,1,22,7,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/27/20,40,214,93,1,23,7,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/28/20,41,228,93,1,23,7,4,4,5,1,...,0,0,0,0,0,0,0,0,0,0
2/29/20,42,241,102,1,25,8,4,7,9,1,...,0,0,0,0,0,0,0,0,0,0
3/1/20,42,256,106,1,29,8,6,7,9,1,...,0,0,0,0,0,0,0,0,0,0
3/2/20,43,274,108,1,29,8,6,9,9,1,...,0,0,0,0,0,0,0,0,0,0
3/3/20,43,293,110,1,36,9,13,9,11,1,...,0,0,0,0,0,0,0,0,0,0
3/4/20,43,331,110,1,50,12,22,10,11,1,...,0,0,0,0,0,0,0,0,0,0
3/5/20,47,360,117,1,50,13,22,10,13,1,...,0,0,0,0,0,0,0,0,0,0
3/6/20,48,420,130,1,83,21,26,10,13,1,...,0,0,0,0,0,0,0,0,0,0
3/7/20,50,461,138,1,93,21,28,11,13,1,...,0,0,0,0,0,0,0,0,0,0
3/8/20,50,502,150,1,99,27,38,11,15,2,...,0,0,0,0,0,0,0,0,0,0
3/9/20,50,511,150,1,117,32,48,15,15,2,...,0,0,0,0,0,0,0,0,0,0
3/10/20,53,581,160,1,129,32,55,18,18,2,...,0,0,0,0,0,0,0,0,0,0
3/11/20,59,639,178,1,149,39,65,21,20,3,...,1,1,1,3,1,2,1,1,1,1

In [108]:
df.to_csv('time_series_19-covid_Merged.csv')